include Makefile.inc

CC := mipsel-gcw0-linux-uclibc-cc
SYSROOT := $(shell $(CC) -print-sysroot)

CFLAGS += $(shell $(SYSROOT)/usr/bin/sdl-config --cflags)
LIB += $(shell $(SYSROOT)/usr/bin/sdl-config --libs)

%.o:	%.c
	$(CC) $(CFLAGS) $(INC) $(LIB) -o $@ -c $<

all:	$(OBJ)
	$(CC) $(OBJ) -o $(OUT) $(CFLAGS) $(INC) $(LIB)  

clean:
	$(RM) $(OUT) $(OBJ)

